### ISSUE TITLE
Failed to extract native libraries

### ISSUE THREAD

**Issue by guiyanakuang** [hydraulic-software/conveyor#116]
**Describe the bug**
Build mac-app with extract-native-libraries = true, all other jar packages are successfully extracted except selenium-manager-4.22.0.jar.

**To Reproduce**
Steps to reproduce the behavior.
1. Create a Compose Multiplatform project
2. Depend on selenium-manager-4.22.0.jar
3. configure extract-native-libraries
4. `conveyor -Kapp.machines=mac.amd64 make mac-app`
5. check `Resources/selenium-manager-4.22.0.jar` and `runtime/Contents/Home/lib/`

**Expected behavior**
Successfully extract the executable and place it in runtime/Contents/Home/lib/

**Additional context**
Using conveyor 14.3

**Comment by mikehearn** [comment]
Could you please provide the Maven coordinates of this library? It's not clear where to get this JAR from.

**Comment by guiyanakuang** [comment]
Here are the maven coordinates for it.
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-manager</artifactId>
    <version>4.22.0</version>
</dependency>
```

**Comment by mikehearn** [comment]
Thanks. I'm afraid this isn't a bug - native library extraction is only for libraries. The native files in that JAR are executables, not libraries. This isn't a minor difference: Conveyor can do native library extraction because libraries are looked up using `System.loadLibrary` and thus changes to the location can be abstracted (somewhat, sometimes). There's no equivalent for EXE files, so if we extracted them then the library would just break. If you want to extract these so they get signed, you'll unfortunately have to do this using some custom build logic, and maybe update the library as well.

I'm not sure extraction would do much in this case anyway, as apparently the purpose of these binaries is to download more binaries to the cache, so the main reasons to use extraction (startup time, signing, not littering the user's home dir) won't apply here, that will happen anyway.

**Comment by guiyanakuang** [comment]
When notarizing the Mac application, I encountered an issue where it requested me to sign the executable within selenium-manager. I have already handled this issue manually. Thank you very much for your help.
