### ISSUE TITLE
Build inconsistencies on JVM

### ISSUE THREAD

**Issue by magdkudama-merlyn** [hydraulic-software/conveyor#49]
I'm using USB4Java libraries in my project. In order to respect JAR-stripping, I'm using the following:

```
app {
  jvm {
    system-properties {
      "org.usb4java.LibraryName" = "usb4java"
    }
  }
}
```

The codebase is reading this env variable, and loading the library from the location (using `System.loadLibrary`). This works on Mac. When running on Windows (haven't tested yet on Linux), there's a linking issue, as it's expecting `usb4java` to be present, but `libusb4java` is instead. That's the same case for Mac, but it works fine there as the loader will check for the `lib` prefix:

<img width="339" alt="Screenshot 2023-02-07 at 11 51 02" src="https://user-images.githubusercontent.com/111091128/217224909-adaad6f7-2cf0-4d74-acf6-0d8db190ee00.png">

I tried building using:

```
"org.usb4java.LibraryName" = "libusb4java"
```

And that now works on Windows, but not on Mac:

<img width="241" alt="Screenshot 2023-02-07 at 11 54 49" src="https://user-images.githubusercontent.com/111091128/217225742-4d20f261-6260-42ed-b565-47e94c6ae7a3.png">

Is there a way in Conveyor to specify `system-properties` per OS/arch combination? Or am I missing something here?

**Comment by mikehearn** [comment]
Hi,

Thanks for the report. This is actually a bug in usb4java - it's using UNIX library naming conventions even on Windows, which goes against the Java spec. It's hidden because normally the library handles its own extraction and then points the JVM directly at the library file. 

In the next Conveyor release we switch by default to signing libraries in place, which should fix it at a cost of some lost performance. Unfortunately there are just far too many buggy JNI loading mechanisms out there, and so library extraction will become opt-in. 

So there are two options:

1. Wait for the next release. Probably it will come out next week but we can't promise anything.
2. Modify libusb4java-win32 jar to use a DLL without the "lib" prefix (or change its loading code). It looks like the library is unmaintained, sadly.

Sorry there isn't better news!

**Comment by magdkudama-merlyn** [comment]
Thanks @mikehearn, I didn't know there was a spec, I'll read about it. This isn't bad news anyway, it is what it is; `usb4java` is basically an unmaintained library.  I think we'll go for option 1, but at least we know why it's not working on Windows.

I'll close this, and we'll wait for the next release of Conveyor.

**Comment by mikehearn** [comment]
Ah yeah, the Java "spec" is defined by a set of standards documents (the Java Language Spec, the JVM Spec) and then also the javadocs, which are defined as the "spec" for the API. It's why the JavaDocs sometimes miss out crucial information about the implementation everyone actually uses, because technically it's not defined by the spec :(
