### ISSUE TITLE
JVM for Windows Intel: Could not jlink: Module java.annotation not found

### ISSUE THREAD

**Issue by zacharee** [hydraulic-software/conveyor#60]
**Describe the bug**
I'm trying to create a build for Windows using Conveyor. On 8.2, it would build without issues. With 9.1, I get the following error:

```JVM for Windows Intel: Could not jlink: Module java.annotation not found```

**To Reproduce**
1. Clone this repo: https://github.com/zacharee/ArcadyanKVD21Control.
2. Run `conveyor make window-zip` (or `site`, or anything that does a Windows build).
3. The process will error out.

I tested on both Windows 11 and macOS 13.5.

**Expected behavior**
The build should succeed.

**Screenshots**
M/A

**Desktop (please complete the following information):**
 - OS: macOS 13.5, Windows 11.
 - Browser: N/A.
 - Version: Conveyor 9.1.

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by mikehearn** [comment]
Thanks for the bug report! A workaround is to add this to your config:

```
app.jvm.modules += -java.annotation
```

We tried it with your project and this let the build complete. We didn't try running the app itself because it starts at a login screen.

The problem is that the code assumes any module starting with `java.` comes with the JDK. This one is an exception for historical reasons (also `java.activation` I think). So we'll get that fixed.

**Comment by zacharee** [comment]
Thanks, that made it build successfully!
