### ISSUE TITLE
bug: Mac App for Intel: JAR files were imported but no JVM inputs were supplied for 'mac.amd64'

### ISSUE THREAD

**Issue by Mouwrice** [hydraulic-software/conveyor#72]
**Describe the bug**
As a result of an issue with compose multiplatform https://github.com/JetBrains/compose-multiplatform/issues/3411
I had to set the `jvmToolchain(11)`, so to version 11. Now conveyor is able to read this and get the JDK's for Linux and Windows platform but not for MacOS for some reason. It does work with `jvmToolchain(17)` but this cannot be used for the moment due to linked issue.

Can be reproduced by going on my repository which has this issue linked with instructions:
https://github.com/Mouwrice/proguard-core-visualizer/issues/62

**Expected behavior**
Conveyor to automatically find the correct java toolchain and apply it.

**Screenshots**
![image](https://github.com/hydraulic-software/conveyor/assets/56763273/96aa592d-e438-466b-a03f-4be94a9ba9e8)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Comment by mikehearn** [comment]
Try adding something like this to your gradle build:

```
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
        vendor.set(JvmVendorSpec.AMAZON)
    }
}
```

The issue is that, in fact, the OpenJDK 11 project is maintained by (iirc) Red Hat and has stopped offering macOS builds quite some time ago. So Conveyor is correct when it says you haven't supplied a JDK11, although the error message needs to make it much clearer why you haven't supplied one.
